package edu.depaul.se.servlet;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

import javax.servlet.ServletContextEvent;
import javax.servlet.ServletContextListener;
import javax.servlet.annotation.WebListener;

import edu.depaul.se.account.jpa.AccountManager;

@WebListener
public class ServletInitializer implements ServletContextListener {

	public void contextDestroyed(ServletContextEvent arg0) {
	}

	public void contextInitialized(ServletContextEvent arg0) {
		Connection connection;
		try {
            try {
				Class.forName("org.hsqldb.jdbcDriver");
			} catch (ClassNotFoundException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			connection = DriverManager.getConnection("jdbc:hsqldb:mem:.", "sa", "");
			Statement statement = connection.createStatement();
			statement.execute("create table accounts(id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100) PRIMARY KEY, name varchar(50), balance float)");
			AccountManager manager = new AccountManager();
			manager.createAccount("John", 100);
			manager.createAccount("Paul", 100);
			manager.createAccount("George", 100);
			manager.createAccount("Ringo", 100);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
}
