package edu.depaul.se.servlet;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public abstract class MockServletInitializer {

	static {
        try {
	        Connection connection = DriverManager.getConnection("jdbc:hsqldb:mem:.", "sa", "");
	        Statement statement = connection.createStatement();
        	statement.execute("create table accounts(id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100) PRIMARY KEY, name varchar(50), balance float)");
        }
        catch (SQLException sql) {
        	System.out.println(sql.toString());
        }
		
	}
}
